version: '3.7'

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=mysecretpassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - /Users/shengyip/Workspace/mysite/db_data_pg12:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    webserver:
        image: psyking841/mysite:latest
        environment:
            - POSTGRES_HOST=postgres
        depends_on:
            - postgres
        ports:
            - "8000:8000"
